### ISSUE TITLE
errorCode

### ISSUE THREAD

**Issue by Steven-79** [MartinGris/node-red-contrib-skoda-connect#1]
first of all, many thanks for creating the node.

I use it to get the information from my Octavia IV.
Since the last update i got these three errors: (the fin is replaced with XXX)

{"error":{"errorCode":"climatisation.auth.forbidden","description":"The service: rclima_v1 for VIN: XXX could not be found."}}

{"error":{"errorCode":"batterycharge.auth.forbidden","description":"The service: rbatterycharge_v1 for VIN: XXX could not be found."}}

{"error":{"errorCode":"departuretimer.auth.forbidden","description":"The service: timerprogramming_v1 for VIN: XXX could not be found."}}

**Comment by MartinGris** [comment]
Hi. Are you able to use these features from the skoda connect app? So it is possible to start the climater for example? Or can you set a departure time when the battery should be fully loaded and the climater heats on to a specified temperature?

**Comment by Steven-79** [comment]
Hello Martin, 
no, my vehicle is not electric or a hybrid. 
There is also no parking heater, therefore i cannot use these parameters with the connect app.

Unfortunately the whole node doesn't work for me right now. No data other than the three errors are output.

**Comment by MartinGris** [comment]
Hi. I'm querying more information from eletric car specific features since the last update. I will make them optional with the next commit. In the meantime you can switch to the previous version.
Sorry for the trouble

**Comment by Steven-79** [comment]
Okey, thank you for your work and support ...
This is a great node!

**Comment by MartinGris** [comment]
Hi, the node can now be configured to query only the functions available for your car. Please check and give me a feedback

**Comment by Steven-79** [comment]
Hello, now it's working again for me.
Thank you for your work, really great...
