### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by PP-JN-RL** [MartinGris/node-red-contrib-skoda-connect#3]
Thanks for creating this great add-on.
There is a slight issue when installing it on the latest build of Node-RED.

It comes up with the following error message: 
_SyntaxError: Unexpected token = (line:7)
SyntaxError: Unexpected token = (line:7)_

The affected command is Skoda-Get & Skoda-Set

**Comment by MartinGris** [comment]
Hi, 
I just updated to Node-Red v1.3.5 and for me it's still working fine.

The SyntaxError indicates that there is a problem with your node js version or your whole installation. I'm using node js v12.22.1.

Hope that helps a little bit

**Comment by PP-JN-RL** [comment]
I just had a look on my docker container and you are correct, my version is 10.241.
So I will need to find an image with a more up to date version of Node.js

Thanks for your help, much appreciated.

```
Welcome to Node-RED
===================
19 Jun 11:45:39 - [info] Node-RED version: v1.3.5
19 Jun 11:45:39 - [info] Node.js  version: v10.24.1
19 Jun 11:45:39 - [info] Linux 5.10.17-v7l+ arm LE
19 Jun 11:45:39 - [info] Loading palette nodes
19 Jun 11:45:42 - [warn] ------------------------------------------------------
19 Jun 11:45:42 - [warn] [node-red-contrib-skoda-connect/skoda-get] SyntaxError: Unexpected token = (line:7)
19 Jun 11:45:42 - [warn] [node-red-contrib-skoda-connect/skoda-set] SyntaxError: Unexpected token = (line:7)
19 Jun 11:45:42 - [warn] ------------------------------------------------------
19 Jun 11:45:42 - [info] Settings file  : /data/settings.js
19 Jun 11:45:42 - [info] Context store  : 'default' [module=memory]
19 Jun 11:45:42 - [info] User directory : /data
19 Jun 11:45:42 - [warn] Projects disabled : editorTheme.projects.enabled=false
19 Jun 11:45:42 - [info] Flows file     : /data/flows.json
```
