### ISSUE TITLE
Authentication error - malformed request

### ISSUE THREAD

**Issue by gerritfries** [MartinGris/node-red-contrib-skoda-connect#4]
First of all I'd like to thank you for your great work!

Since a few days I can't receive my car's data any longer. I haven't changed anything in the setup and the error just occurred suddenly.

`"{"error":{"errorCode":"gw.error.authentication","description":"Malformed request"}}"`

Any help would be appreciated!

**Comment by MartinGris** [comment]
Hi Gerrit,

thanks for reporting this issue! I've fixed it with the latest version 1.2.10.

Greetings
Martin
