### ISSUE TITLE
Can't login any more

### ISSUE THREAD

**Issue by MHagreis** [MartinGris/node-red-contrib-skoda-connect#5]
get an error sins about 7 day's can you help me a bit
account is checked and ok but not getting the data?

9/27/2021, 8:16:42 AMnode: My-Car Parking
msg : number
403
9/27/2021, 8:16:42 AMnode: My-Car Parking
msg : number
400
9/27/2021, 8:16:42 AMnode: My-Car Parking
msg : string[83]
"{"error":{"errorCode":"gw.error.authentication","description":"Malformed request"}}"

**Comment by MHagreis** [comment]
![image](https://user-images.githubusercontent.com/50264856/134854622-e9c00f1e-93f2-490d-8b15-aee67b3d4329.png)

**Comment by MartinGris** [comment]
Please check out the newest version. The issue should be solved #4

**Comment by MHagreis** [comment]
Thanks didn't know that i needed to do that manual, great help
