### ISSUE TITLE
syntax error in node-red-contrib-skoda-connect 1.3.0

### ISSUE THREAD

**Issue by alexlinno** [MartinGris/node-red-contrib-skoda-connect#8]
Thanks for your efforts. However when loading the plugin through the palette i get a syntax error
SyntaxError: Unexpected token = (line:7)
running node red 1.2.7
Thanks

**Comment by MartinGris** [comment]
Hi,

please see Issue #3  and check your node js version

**Comment by alexlinno** [comment]
excellent.thanks for the quick reply and sorry for not searching the closed issues

**Comment by alexlinno** [comment]
nodejs upgraded

**Comment by MartinGris** [comment]
You're welcome! no problem ;)
