### ISSUE TITLE
No Login Form found. Please check your E-Mail in the app.

### ISSUE THREAD

**Issue by MHagreis** [MartinGris/node-red-contrib-skoda-connect#9]
From this afternoon i got the following error: No Login Form found. Please check your E-Mail in the app.
login checked via the website but that is, ok?

did skoda change something again :(
![image](https://user-images.githubusercontent.com/50264856/151665460-ba5dc28a-c833-49f7-974a-2d20ffa2f328.png)

![image](https://user-images.githubusercontent.com/50264856/151665415-195d1c1f-ad07-4372-8e9c-b4d21ff8292e.png)

![image](https://user-images.githubusercontent.com/50264856/151665438-085fb56b-e98d-4c72-b15d-f7b7dd51ff77.png)

thanks

**Comment by alexlinno** [comment]
I suddenly have this problem too..but worse my node.red will not start
29 Jan 16:49:19 - [info] [tcp in:Node-RED Client] connection lost to 192.168.0.16:23
29 Jan 16:49:19 - [error] [skoda-get:b9e6c902.7a11e8] No Login Form found. Please check your E-Mail in the app.
29 Jan 16:49:19 - [red] Uncaught Exception:
29 Jan 16:49:19 - TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at /home/pi/.node-red/node_modules/node-red-contrib-skoda-connect/lib/skoda-library.js:134:22
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SkodaLibrary.connect (/home/pi/.node-red/node_modules/node-red-contrib-skoda-connect/lib/skoda-library.js:124:13)
    at async SkodaConnectNode._inputCallback (/home/pi/.node-red/node_modules/node-red-contrib-skoda-connect/nodes/skoda-get.js:24:13)
nodered.service: Main process exited, code=exited, status=1/FAILURE

**Comment by alexlinno** [comment]
removed skoda package and we are up and running again

**Comment by MartinGris** [comment]
Hi,

login procedure was changed by skoda. It is adapted in the 1.3.1 version which should be online in a couple of minutes.

@alexlinno I think you have an additional problem. My node red installation is not crashing

**Comment by MHagreis** [comment]
@MartinGris  Thank you for your Superb support this is really great.
@alexlinno indeed my node red didn't crash as well.

waiting now for the release to come true keep you posted 👍

**Comment by MHagreis** [comment]
@MartinGris Hereby i can confirm that you made my day thankyou and update is indeed published worked like a charm
